name: Main
on:
  - pull_request
  - push
jobs:
  common:
    name: Dependencies, Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node: ${{ matrix.node }}

      - name: Run unit tests
        run: npm test

  build-app:
    name: Build application
    needs:
      - common
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12' ]
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node: ${{ matrix.node }}

      - name: Build
        uses: ./.github/actions/build-app

      - name: Save build directory
        uses: actions/upload-artifact@v3
        with:
          name: 'build'
          path: "dist"
          if-no-files-found: error
          retention-days: 2

  test-app:
    name: Test application
    needs:
      - build-app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [ 'chromium', 'firefox', 'electron' ]
        node: [ '12' ]
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node: ${{ matrix.node }}

      - name: Download build directory
        uses: actions/download-artifact@v3
        with:
          name: 'build'
          path: "dist"

      - name: Run functional tests
        uses: './.github/actions/test-app'
        with:
          browser: ${{ matrix.browser }}
          cypress-project-id: ${{ secrets.CYPRESS_PROJECT_ID }}
          cypress-record-key: ${{ secrets.CYPRESS_RECORD_KEY }}
          node: ${{ matrix.node }}

  deploy-to-heroku:
    name: Deploy to Heroku
    if: github.event_name == 'push' && github.branch == 'refs/heads/master'
    needs:
      - build-app
    uses: './.github/workflows/deploy-to-heroku.yml'
    with:
      node: 12
    secrets:
      CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
